waffles_io/config/routes.rb
Rails.application.routes.draw do
  root 'orders#index'

  get 'orders/new' => 'orders#new', as: :new_order
  post 'orders' => 'orders#create', as: :orders
  get 'orders/:id' => 'orders#show', as: :order
  get 'orders/:id/edit' => 'orders#edit', as: :edit_order
  patch 'orders/:id' => 'orders#update'
  delete 'orders/:id' => 'orders#delete'

end

waffles_io/app/models/order.rb
class Order < ActiveRecord::Base

  validates :customer_name, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true }, inclusion: {in: 1..5}
  validates :waffle_type, presence: true

end

waffles_io/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

waffles_io/app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find params[:id]
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find params[:id]
  end

  def create
    @order = Order.new params.require(:order).permit(:quantity, :waffle_type, :special_instructions, :customer_name)
    # order.quantity = params[:order][:quantity]
    # order.waffle_type = params[:order][:waffle_type]
    # order.special_instructions = params[:order][:special_instructions]

    if @order.save
      redirect_to root_path
    else
      # order did not save
      render :new
    end
  end

  def update
    @order = Order.find params[:id]
    if @order.update params.require(:order).permit(:quantity, :waffle_type, :special_instructions, :customer_name)
      redirect_to order_path(@order)
    else
      # order did not save
      render :edit
    end
  end

  def delete
    @order = Order.find params[:id]
    @order.destroy
    redirect_to root_path
  end
end

waffles_io/app/helpers/application_helper.rb
module ApplicationHelper
end

waffles_io/app/helpers/orders_helper.rb
module OrdersHelper
end

waffles_io/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WafflesIo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to 'Home', root_path %>
<%= yield %>

</body>
</html>

waffles_io/app/views/orders/_form.html.erb
<% if @order.errors.any? %>
  <div class="errors">
    <h3>Sorry brah, no waffles for you until you fix:</h3>
    <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @order do |f| %>

  <div>
    <%= f.label :customer_name %>
    <%= f.text_field :customer_name %>
  </div>

  <div>
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </div>

  <div>
    <%= f.label :waffle_type %>
    <%= f.select :waffle_type, ["belgian", "Gold Debloom", "Chocolate Chip"], prompt: true %>
  </div>

  <div>
    <%= f.label :special_instructions %>
    <%= f.text_area :special_instructions %>
  </div>

  <%= f.submit %>

<% end %>

<% if false %>

<form action="/orders" method="post">

  <div>
    <label for="quantity">Quantity</label>
    <input type="text" name="quantity"></input>
  </div>

  <div>
    <label for="waffle_type">Waffle Type</label>
    <select name="waffle_type">
      <option value="belgian">Belgian Waffle</option>
      <option value="debloom">Gold Debloom</option>
      <option value="cocoa">Chocolate Chip</option>
    </select>
  </div>

  <div>
    <label for="special_instructions">Special Instruction</label>
    <textarea name="special_instructions"></textarea>
  </div>

  <div>
    <input type="submit" value="Save new order"></input>
  </div>

</form>

<% end %>

waffles_io/app/views/orders/edit.html.erb
<h1>You are editing: <%= @order.customer_name%>'s order</h1>

<%= render partial: 'form' %>

waffles_io/app/views/orders/index.html.erb
<h1>Orders</h1>

<%= link_to 'Add New Order', new_order_path %>

<p>List of Orders</p>

<ul>
  <% @orders.each do |order| %>
    <li>
      <%= order.quantity %> <%= order.waffle_type %>
      <%= link_to "Show", order_path(id: order.id) %>
      <%= link_to 'Edit', edit_order_path(id: order.id) %>
    </li>
  <% end %>
</ul>

waffles_io/app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render partial: 'form' %>

waffles_io/app/views/orders/show.html.erb
<h1>Order ID: <%= @order.id %></h1>

<ul>
  <li><strong>Customer Name</strong> <%= @order.customer_name %></li>
  <li><strong>Quantity</strong> <%= @order.quantity %></li>
  <li><strong>Waffle Type</strong> <%= @order.waffle_type %></li>
  <li><strong>Special Instructions</strong> <%= @order.special_instructions %></li>
</ul>

<p>
  <%= link_to "Edit this Order", edit_order_path(id: @order.id) %>
</p>

<p>
  <%= link_to 'Delete this order', order_path(@order), method: 'delete', data: {confirm: 'Are you sure you want to delete?'}%>
</p>